// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sayHello.proto

package protobuf.hello;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
