// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sayHello.proto

package protobuf.hello;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
